### ISSUE TITLE
TAG_End as type for empty lists

### ISSUE THREAD

**Issue by NiclasOlofsson** [fragmer/fNbt#12]
According to the "spec" at http://minecraft.gamepedia.com/NBT_format 

"It may also be the type of empty List tags."

In the code for NbtList it doesn't allow END tags as type for the list hence barfs on some (many) region files.

**Comment by fragmer** [comment]
Thanks for bringing this to my attention, Niclas! I was not aware of this quirk. I'll have it fixed this week.

**Comment by NiclasOlofsson** [comment]
I can provide a pull for the fix if that helps speed up the release? About 50% of the worlds loding are affected by this right now. But i guess that the actual "fix" is not what takes time, right?

**Comment by fragmer** [comment]
The hard part is finding the time :)

A quick fix (in the pull request) is possible, but I need to check for side effects, and add various sanity checks and unit tests (for example, it should not be possible to have a non-empty list of end-tags). And then package and distribute it.

I expect to have it all done within 24 hours though. I'm sorry about the wait!

**Comment by NiclasOlofsson** [comment]
Yeah, was a very dirty quick fix :-) The changes you made looks good. I'll wait for it to update NuGet and then test it.

**Comment by fragmer** [comment]
NuGet update was just pushed!
